# Site settings
title: Blog (For the lack of a better name)
email: harry671003@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The odd one
baseurl: /blog
url: https://harryjohn.github.io
twitter_username: harry671003
github_username: harry671003
minimal_mistakes_skin: contrast

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Kolkata


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Harry John"
  bio    : "The odd one."
  email  : harry671003@gmail.com
  uri    : "https://harryjohn.io"
  avatar : "https://en.gravatar.com/avatar/56c27f3df63adbb2ca07432b29ab36ec?s=200"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/harry671003"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/uglyhelmet"
